name: Ape Testing

default_ecosystem: avalanche

plugins:
  - name: foundry
  - name: avalanche
  - name: alchemy
  - name: etherscan


avalanche:
  default_network: mainnet
  mainnet:
    default_provider: infura
  mainnet_fork:
    default_provider: foundry
    uri: https://avalanche-mainnet.core.chainstack.com/ext/bc/C/rpc/f33804dd98cad6bc454e78ea22d84e82

foundry:
  fork:
    avalanche:
      mainnet:
        upstream_provider: alchemy